all: *.tex
	latexmk -pdf presentation.tex 

clean:
	-rm *.gz
	-rm *.pdf
	-rm *.fdb_latexmk
	-rm *.aux
	-rm *.lot
	-rm *.lof
	-rm *.bbl
	-rm *.toc
	-rm *.blg
	-rm *.log
	-rm *.out
	-rm *.fls
	-rm *.nav
	-rm *.snm
	-rm *.vrb
